[
  {
    address: "Nadzaladevi, Plexanovi, Tbilisi, Ash, 2121, Georgia",
    address_line_1: "Kinoti",
    address_line_2: "Plexanovi",
    city: "Tbilisi",
    country: "Ossetia",
    email: "nametest@gmail.com",
    email_verified: true,
    first_name: "Full",
    full_address: {
      city: "Tbilisi",
      country: "Georgia",
      state_province: "Ash",
      street_address_1: "Nadzaladevi",
      street_address_2: "Plexanovi",
      zip_code: "2121",
    },
    full_name: "Full name",
    fullname: "Full name test",
    last_name: "name test",
    phone: "3232323232",
    phone_verified: false,
    postal_code: "4343",
    state: "State",
    state_province: "Ash",
    status: "pending_verification",
    street_address_1: "Nadzaladevi",
    street_address_2: "Plexanovi",
    sub: "923aa999-dfa8-4ad0-8b2c-23f0b0972b96",
    user_type: "driver",
    van_option: "own",
    zip_code: "2121",
  },
];
